### PR TITLE
Hard-code some exports with built-in syntax

### LINKED ISSUE #368: Documentation for base does not include special items
From trac:

  The documentation for base does not include tuples, lists or arrow. I realise these are special in Haskell, but it seems a shame they aren't documented.
  For tuples, the documentation for base doesn't include them in either Prelude or Data.Tuple, but the documentation for ghc-prim includes them in GHC.Unit and GHC.Tuple. I think the lack of documentation for tuple types is a bug, since it would be relatively easy for them to be documented, and does make the documentation more complete.
  For lists ([], (:)), there is no documentation in either base or ghc-prim. It would be nice if they were documented in Prelude and Data.List, but not if it was too much effort (I can imagine that Haddock can't accept list definitions).
  For the arrow type ->, it's unclear if it can reasonably be documented, so it might be worth thinking about but probably not bothering to document.
  The reason I'm interested in ensuring complete documentation is that Hoogle currently doesn't know about tuple constructors in the base library, but it does know about them in ghc-prim, which seems wrong.

https://ghc.haskell.org/trac/ghc/ticket/4861

### PR DESCRIPTION
**Pull request by harpocrates**
This means that `[]`, `(~)`, `(->)` will show up in generated documentation.
This is a gross patch to work around the fact that Haskell lacks the
concrete syntax to put these things in export lists. As far as gross
patches go, it is pretty short.

  * Docs for `GHC.Prim` now include `(->)` (morally it should, since its interface does)
  * Docs for `GHC.Types` now include `[]([], (:))` and `(~)` (as per the comments in its export list)
  * Docs for `Prelude` now include `(->)` and `[]([], (:))` (at the top of the "Basic data types" section)
  * Docs for `Data.Tuple` now include boxed tuples of arity 0 to 15 (I'm capping at 15 since that's what the report gives)
  * Docs for `Data.List` now include `[]([], (:))`

Fixes #368.

### CODE REVIEW

File: haddock-api/src/Haddock/Interface/Create.hs [hunk 1]
```diff
@@ -165,6 +193,30 @@ createInterface mod_iface flags modMap instIfaceMap = do
...
+    --   * "Prelude" should export @(->)@ and @[]([], (:))@
+    --   * "Data.Tuple" should export tuples up to arity 15
+    --
+    listAvail = [ AvailTC listTyConName
+                          [listTyConName, nilDataConName, consDataConName]
+                          [] ]
+    funAvail  = [ AvailTC funTyConName [funTyConName] [] ]
+    eqAvail   = [ AvailTC eqTyConName [eqTyConName] [] ]
+    tupsAvail = [ AvailTC tyName [tyName, datName] []
+                | i<-[0..15]
```
Comment (sjakobi) [inline haddock-api/src/Haddock/Interface/Create.hs]: Can you add a comment on why you chose arities 0 to 15 here? I've seen `mAX_TUPLE_SIZE` in ghc but I don't think it's a better limit than 15.

Personally I'm a bit surprised that we have tuples of arity 0 and 1 but I may have simply missed the news.

**Comment by harpocrates** [comment]
> I'm really looking forward to finding the relevant instances documented with these special types! :) Does this already work?

You bet it does, although the generated docs will look even nicer after the following land:

  * https://phabricator.haskell.org/D5167 adds docs to `data a -> b` and fixities to `->` and `:`
  * https://phabricator.haskell.org/D5158 adds docs and examples to `data [] a`

> Regarding my inline comment: I've seen your explanation in the commit message but I think it would be good to have it in the code too!

Good point; added an explanation to `Note [Exporting built-in items]`.

**Comment by sjakobi** [comment]
Great work! Cheers! :D
